# Generated by Django 5.0.6 on 2024-06-29 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_author_blogpost_document_employee_event_measurement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['publication_date'], 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='post', to='pages.author'),
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('books', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='post', to='pages.book')),
            ],
            options={
                'verbose_name_plural': 'Видавництва',
            },
        ),
    ]
